# Generated by Django 2.1.1 on 2018-10-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('codigo', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='imagen/%Y/%m/%d/')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
