# Generated by Django 2.1.1 on 2018-10-01 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ficha_tecnica',
            field=models.ImageField(blank=True, null=True, upload_to='ficha_tecnica/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='productos.Categoria'),
        ),
    ]
