# Generated by Django 2.1.1 on 2018-10-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_auto_20181004_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ficha_tecnica',
            field=models.FileField(blank=True, null=True, upload_to='ficha_tecnica/%Y/%m/%d/'),
        ),
    ]
